In [5]:
class student:
    name="xyz"
    age=0
    def study (self):
        print("study 3 hour",self.name)
        

In [13]:
##incapsulation
class student:
    name="xyz"
    age=0
    def study (self):
        print("study 3 hour",self.name)
        self.sleep()

    def sleep (self):
        print("sleep 1 hour")

obj=student()
obj.study()
        

study 3 hour xyz
sleep 1 hour


In [17]:
##inheritance
class A:
    def show(self):
        print("this is show method")

class B(A):
    def demo (self):
        print("demo method")

class C(A):
    pass

class D(B,C):
    pass

obj= C ()
obj.show()
obj.demo()


this is show method


AttributeError: 'C' object has no attribute 'demo'

In [24]:
## method overiding
class Bird:
 def intro(self):
     print("There are many types of birds.")

def flight (self):
     print("most of the birds can fly but some cannot.")

class sparrow(Bird):
 def flight (self):
     print("i can fly")

class ostrich(Bird):
  def flight(self):
         print("i can't fly")

In [25]:
## incapsulation
class A:
 __name="abc"

class B (A):
  def show(self):
   print("This is show method", self.name)

obj=B()
obj.show()

AttributeError: 'B' object has no attribute 'name'

In [3]:
print("line 1")
print("line 2")
print("line 3")
print("line 3")
num1=int (input("Enter first number :"))
num2=int (input("enter the division number:"))

print(num1/num2)
open("anudip.txt")

print ("something went wrong")

print(" line 6")

line 1
line 2
line 3
line 3
0.6


FileNotFoundError: [Errno 2] No such file or directory: 'anudip.txt'

In [6]:
print("line 1")
print("line 2")
print("line 3")
print("line 3")
num1=int (input("Enter first number :"))
num2=int (input("enter the division number:"))

try:
   print(num1/num2)
except:
    print("something went wrong")
else:
    print("Else block")
finally:
    print("Finally block")

print("Line 6")

line 1
line 2
line 3
line 3
0.6
Else block
Finally block
Line 6


In [2]:

user_input = input("Please enter an integer: ")
try:
        # Attempt to convert the input to an integer
        value = int(user_input)
        print(f"You entered the integer: {value}")
except ValueError:
        # Raise a ValueError if the input cannot be converted to an integer
        raise ValueError("The input is not a valid integer. Please enter a valid integer.")



You entered the integer: 12


In [4]:
def agecheck (age):
    if age>=18:
        print("you can vote")
    else:
       raise ValueError("you can't vote")   


    try:
        agecheck(14)
    except ValueError as e :
        print(e) 

In [9]:
import numpy as np

a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])

print("a array",a)
print("b array",b)
print("c array",c)
print("d array",d)

print("a array dimen",a. ndim)
print("b array dimen",b . ndim)
print("c array dimen",c . ndim)
print("d array dimen",d . ndim)

a array 42
b array [1 2 3 4 5]
c array [[1 2 3]
 [4 5 6]]
d array [[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]
a array dimen 0
b array dimen 1
c array dimen 2
d array dimen 3


In [11]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])

sarr=arr[1:5]
print(arr)
print(sarr)

sarr[2]=100

print(arr)
print(sarr)

[1 2 3 4 5 6 7]
[2 3 4 5]
[  1   2   3 100   5   6   7]
[  2   3 100   5]


In [13]:
import numpy as np

arr = np. array([1,2,3,4,5])
x= arr. copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [15]:
import numpy as np
arr= np.array([1,2,3,4,5])
x= arr.view()
arr[0]= 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [1]:
import numpy as n
arr5 =np.diag((3,4,1,6))
print(arr5)
print(arr5.ndim)
print(arr5.shape)

NameError: name 'np' is not defined

In [4]:
import numpy as np
arr= np.array([[1,2,3],[4,5,6],[4,5,6]])
print(np.diag(arr))
print(np.diag)((3,9,5))

[1 5 6]
<function diag at 0x107a7b380>


TypeError: 'NoneType' object is not callable

In [6]:
##This function generates array  of specified shape and fills 
rand=n.random.rand(4)
print(rand)
rand=n.random.rand(2,3)
print(rand)

arr=n.random.randint(0,100,12)
print(arr)

[0.17282343 0.02416376 0.58050086 0.93788019]
[[0.01033516 0.65955533 0.62376445]
 [0.84144157 0.30955037 0.84749635]]
[ 2 60  0 47 91 17 45 75 73 75 97 70]


In [8]:
##The reshape function in numpy allows you to change the shape of an array without changing its data.
arr=n.random.randint(0,100,12)
print(arr)
arr=arr.reshape(4,3)
print(arr)
print("Array vaues is",arr[0][1])
print("Array vaues is",arr[1][0])
print(arr.shape)
arr=arr.reshape(-1,4)
print(arr)
arr=arr.reshape(2,-1)
print(arr)

[59 29 29 92 15 25 91 93 84 45 33 93]
[[59 29 29]
 [92 15 25]
 [91 93 84]
 [45 33 93]]
Array vaues is 29
Array vaues is 92
(4, 3)
[[59 29 29 92]
 [15 25 91 93]
 [84 45 33 93]]
[[59 29 29 92 15 25]
 [91 93 84 45 33 93]]


In [10]:
import numpy as n
arr=n.array([1,20,5,9,3,4,8,5,6,2,25,2,2265,3,33])
slicing=arr[4:9]
print("newslicing",slicing)
print("new array",arr)
print(type(slicing))
print(type(arr))
slicing[:]=0
print("old slicing",slicing)
print("old array",arr)


newslicing [3 4 8 5 6]
new array [   1   20    5    9    3    4    8    5    6    2   25    2 2265    3
   33]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
old slicing [0 0 0 0 0]
old array [   1   20    5    9    0    0    0    0    0    2   25    2 2265    3
   33]


In [12]:
import numpy as np

arr=n.arange(1,15)
print(arr)
print(arr[arr%2==0])


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 2  4  6  8 10 12 14]


In [20]:
ar1 =np.arange(1,15)
print(ar1)
print(ar1%2 == 0)
print(ar1%2 != 0)
print(ar1[ar1>8])
ar1=ar1([ar1%2== 0])
print(ar1)
ar1 =np.arange(1,8)
print(ar1+2)
print(ar1*2)
print(ar1**2)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[False  True False  True False  True False  True False  True False  True
 False  True]
[ True False  True False  True False  True False  True False  True False
  True False]
[ 9 10 11 12 13 14]


TypeError: 'numpy.ndarray' object is not callable

In [21]:
import numpy as np
n .randomseed(122)
mat=n.random.randint(1,21,9).reshape(3,3)
print(mat)
print(n.sum(mat))
print(n.cumsum(mat))
print(n.min(mat))
print(n.max(mat))


AttributeError: module 'numpy' has no attribute 'randomseed'

In [1]:
Import numpy as n 

n.random.seed (122)

mat =n.random.randint (1,21,10)

print (mat)

n.random.shuffle (mat)

print(mat)

print (n.unique (mat, return_index=True,return_counts=True))

print(n.unique(mat).size)

SyntaxError: invalid syntax (1830286760.py, line 1)

In [4]:
##numpy sort 
import numpy as np
arr=np.array([3,1,2,4,5])
sorted_arr=np.sort(arr)
print("sorted array(ascending):",sorted_arr)
sorted_arr_desc = np .sort(arr)[::-1]
print ("sorted array(descending);",sorted_arr_desc)



sorted array(ascending): [1 2 3 4 5]
sorted array(descending); [5 4 3 2 1]


In [7]:
import numpy as np
matrix=np.array([[3,1,2],[6,5,4]])
sorted_matrix=np.sort (matrix , axis =1)
print("sorted array (ascending):",sorted_arr)

sorted array (ascending): [1 2 3 4 5]


In [9]:
import numpy as np
arr1 = np . array([[1,2],[3,4]])
arr2 = np . array ([[5,6],[7,8]])

result = np .concatenate((arr1,arr2), axis=1)
print (result)

[[1 2 5 6]
 [3 4 7 8]]


In [11]:
import numpy as np
arr1 = np .array([1,2,3])
arr2 = np .array([4,5,6])
result = np .hstack((arr1 ,arr2))
print(result)

[1 2 3 4 5 6]


In [14]:
import numpy as np
classB = np .array([70,80,85,95,100])
classB_mean= np. mean(classB)

print('classB score average',classB_mean)

var=np.var(classB)
print('class B variance is',var)
std=np.std(classB)
print('class B variance is', std)

classB score average 86.0
class B variance is 114.0
class B variance is 10.677078252031311


In [16]:
#Test scores of 30 students 
test_scores = np.array([65, 75, 80, 85, 90, 92, 94, 95, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138]) 
median = np.percentile(test_scores, 50) 
print("Median (50th Percentile):",median)

Median (50th Percentile): 109.0


In [18]:
import numpy as np
scores = np . array([85,92,78,88,95,72,89])
np. save('student_scores.npy',scores)
loaded_scores = np.load('student_scores.npy')
print("original scores:", scores)
print("loaded scores:",loaded_scores)

original scores: [85 92 78 88 95 72 89]
loaded scores: [85 92 78 88 95 72 89]
